# Use an official Python runtime as a parent image
FROM python:3.11
#FROM tiangolo/uvicorn-gunicorn:python3.11

# Set the working directory inside the container
WORKDIR /app

# Install any needed packages specified in requirements.txt (if applicable)
COPY ./requirements.txt /app
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app

CMD ["python", "app.py"]
